name: dha_resident_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.0.3+41

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  motion_tab_bar_v2: ^0.3.0
  shrink_sidemenu: ^2.0.0+2-null-safety
  pie_chart: ^5.3.2
  dropdown_textfield: ^1.0.8
  http: ^1.1.0
  provider: ^6.0.1
  fluttertoast: ^8.1.1
  date_format: ^2.0.7
  shared_preferences: ^2.2.0
  marqueer: ^1.4.0
  scroll_snap_list: ^0.9.1
  custom_clippers: ^2.0.0
  flutter_dash: ^1.0.0
  dotted_border: ^2.0.0+3
  overlay_loader_with_app_icon: ^0.0.3
  flutter_html: ^3.0.0-beta.2
  html: ^0.15.4
  intl: ^0.18.1
  awesome_dialog: ^3.1.0
  image_picker: ^1.0.4
  file: ^6.1.4
  geolocator: ^7.0.3
  file_picker: ^5.5.0
  url_launcher: ^6.2.3
  dio: 
  flutter_widget_from_html: ^0.10.4
  shimmer: ^3.0.0
  animated_text_kit:
  flutter_phone_direct_caller: 
  flutter_rating_bar: 
  group_button: ^3.3.1
  intl_phone_field: 
  syncfusion_flutter_pdfviewer: ^23.1.38
  path: ^1.8.3
  package_info: ^2.0.2
  photo_view: ^0.14.0
  insta_image_viewer: ^1.0.2
  flutter_media_downloader: ^1.0.2
  get:
  get_storage:
  upgrader: ^8.3.0
  connectivity: ^3.0.6
  logger: ^2.0.2+1
  async: ^2.11.0

  



dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "asserts/icons/icons.jpg"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - asserts/icons/icon.png
    - asserts/icons/leftmenu.png
    - asserts/icons/checked.png
    - asserts/icons/cross.png
    - asserts/images/cr_frame.png
    - asserts/images/frame.png
    - asserts/images/read.png
    - asserts/images/policeman.png
    - asserts/images/flame.png
    - asserts/images/alert.png
    - asserts/images/complaint1.png
    - asserts/images/contact.png
    - asserts/images/01.png
    - asserts/images/02.png
    - asserts/images/03.png
    - asserts/images/04.png
    - asserts/images/05.png
    - asserts/images/06.png
    - asserts/images/07.png
    - asserts/images/08.png
    - asserts/images/09.png
    - asserts/images/10.png
    - asserts/images/11.png
    - asserts/images/12.png
    - asserts/images/13.png
    - asserts/images/newcomplaint.png
    - asserts/images/trackcomplaint.png
    - asserts/images/morefeatures.png
    - asserts/images/addstaff.png
    - asserts/images/cnicfornt.png
    - asserts/images/cnicback.png
    - asserts/images/date.png
    - asserts/images/pet.png
    - asserts/images/addpet.png
    - asserts/images/feetpet.png
    - asserts/images/petcate.png
    - asserts/images/aleartcomplaint.png
    - asserts/images/aleartfire.png
    - asserts/images/aleartmobile.png
    - asserts/images/aleartphone.png
    - asserts/images/aleartsafety.png
    - asserts/images/mosque.png
    - asserts/images/iconmosque.png
    - asserts/images/lock.png
    - asserts/images/reset.png
    - asserts/images/resetpass.png
    - asserts/images/cat.png
    - asserts/images/dog.png
    - asserts/images/dog2.png
    - asserts/images/parrot.png
    - asserts/images/parakeet.png
    - asserts/images/pdf.png
    - asserts/images/link.png
    - asserts/images/credit.png
    - asserts/images/cperson.png
    - asserts/images/cref.png
    - asserts/images/ccategory.png
    - asserts/images/csubcategory.png
    - asserts/images/cmsg.png
    - asserts/images/cmobile.png
    - asserts/images/ccalendar.png
    - asserts/images/cphone.png
    - asserts/images/domain.png
    - asserts/images/dhaoffice.jpg
    - asserts/images/medical.png
    - asserts/images/ambulance.png
    - asserts/images/reopen.jpg
    - asserts/images/buildings.png
    - asserts/images/building.png
    - asserts/images/rating.png
    - asserts/images/rate.png
    - asserts/images/attachments.jpeg
    - asserts/images/person.jpeg
    - asserts/images/phone.jpeg
    - asserts/images/cell.jpeg
    - asserts/images/calendar.jpeg
    - asserts/images/category.jpeg
    - asserts/images/subcategory.jpeg
    - asserts/images/status.jpeg
    - asserts/images/refrence.jpeg
    



  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
